// ─── Live Integration Probe: DeepSeek vision (image input) contract ─────────
//
// DFD covered: _dfd/ai/ai-provider.md §2c, _dfd/interception/image-interception.md
// Issue: ReLab/Ideas #116 — "[BUG] DeepSeek provider still doesn't support vision
// (should)". Collects live API data that drove the diagnosis:
//   * deepseek-v4-flash-vision-exp accepts OpenAI-style `image_url` content parts
//     (exactly what rockbot serializes via ChatMessage::user_with_images).
//   * Non-vision models (deepseek-v4-pro) reject image parts with HTTP 400 —
//     so DeepSeekProvider must keep stripping images for those models.
//   * Images in system/assistant messages are rejected (400) — a forwarded-body
//     fix must only ever place ImageUrl parts in user messages.
//   * The literal text "[image]" is NOT the reserved placeholder token (HTTP 200),
//     so memory summaries containing "[image]" remain safe for vision models.
//   * Per-image prompt-token cost stays under DeepSeek's 384-token cap.
//
// Ignored by default — requires the workspace `config.toml` (does NOT require the
// bot to be running). Run with:
//
//   cargo test -p rockbot --test deepseek_vision_real -- --ignored --nocapture
//
// NOTE: these are pure API-contract probes against api.deepseek.com; they assert
// nothing about provider internals, so they remain valid both before and after the
// fix that removes DeepSeekProvider's unconditional image stripping.

use std::collections::HashMap;
use std::path::PathBuf;

use rockbot::config::ProviderConfig;
use rockbot::types::{ChatMessage, ContentPart, ImageUrlPayload, MessageContent, Role};
use rockbot::validated::{ConfigUrl, ProviderName};

const DEEPSEEK_VISION_MODEL: &str = "deepseek-v4-flash-vision-exp";
const DEEPSEEK_TEXT_MODEL: &str = "deepseek-v4-pro";

/// 64x48 solid blue PNG (16,128,255) — generated by the probe, statically
/// embedded so the test is self-contained (no image crate / no zlib).
const PNG_BLUE_B64: &str = "iVBORw0KGgoAAAANSUhEUgAAAEAAAAAwCAIAAAAuKetIAAAAYklEQVR4nO3PUQkAIBTAwBfByDbXEH4cwmABbrP2+brhgga0oAEtaEALGtCCBrSgAS1oQAsa0IIGtKABLWhACxrQgga0oAEtaEALGtCCBrSgAS1oQAsa0IIGtKABLWhACx67pM+1DynLTOEAAAAASUVORK5CYII=";

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .to_path_buf()
}

/// Load the `deepseek` chat provider section from the workspace `config.toml`.
fn load_deepseek_config() -> ProviderConfig {
    let config_path = workspace_root().join("config.toml");
    let contents = std::fs::read_to_string(&config_path)
        .unwrap_or_else(|e| panic!("Cannot read config.toml at {:?}: {}", config_path, e));
    let toml: toml::Value = toml::from_str(&contents).unwrap();

    let providers = toml["chat_providers"]
        .as_array()
        .expect("config.toml: [chat_providers] array not found");

    for provider in providers {
        if provider["name"].as_str() == Some("deepseek") {
            let base_url = provider
                .get("base_url")
                .and_then(|v| v.as_str())
                .unwrap_or("https://api.deepseek.com/v1");
            let mut models = HashMap::new();
            if let Some(models_table) = provider.get("models").and_then(|v| v.as_table()) {
                for (k, v) in models_table {
                    if let Some(val) = v.as_str() {
                        models.insert(k.clone(), val.to_string());
                    }
                }
            }
            return ProviderConfig {
                name: ProviderName::try_new("deepseek".to_string()).unwrap(),
                api_key: provider["api_key"].as_str().unwrap_or("").into(),
                base_url: ConfigUrl::try_new(base_url.to_string()).unwrap(),
                basecf_url: None,
                chat_path: None,
                draw_path: None,
                models,
            };
        }
    }
    panic!("deepseek chat_provider not found in config.toml");
}

fn image_data_uri() -> String {
    format!("data:image/png;base64,{PNG_BLUE_B64}")
}

async fn post_chat(
    url: &str,
    api_key: &str,
    body: &serde_json::Value,
) -> (u16, serde_json::Value) {
    let client = reqwest::Client::new();
    let resp = client
        .post(url)
        .header("Authorization", format!("Bearer {api_key}"))
        .header("Content-Type", "application/json")
        .json(body)
        .send()
        .await
        .expect("request to api.deepseek.com should complete");
    let status = resp.status().as_u16();
    let parsed = resp.json::<serde_json::Value>().await.unwrap_or_default();
    (status, parsed)
}

fn chat_body(model: &str, messages: Vec<ChatMessage>) -> serde_json::Value {
    serde_json::json!({
        "model": model,
        "messages": serde_json::to_value(&messages).expect("ChatMessage serializes"),
        "stream": false,
    })
}

fn assistant_with_image() -> ChatMessage {
    ChatMessage {
        role: Role::Assistant,
        content: MessageContent::Multipart(vec![
            ContentPart::Text { text: "look:".into() },
            ContentPart::ImageUrl {
                image_url: ImageUrlPayload { url: image_data_uri(), detail: Some("high".into()) },
            },
        ]),
        name: None,
        tool_calls: None,
        tool_call_id: None,
        reasoning_content: None,
    }
}

fn system_with_image() -> ChatMessage {
    ChatMessage {
        role: Role::System,
        content: MessageContent::Multipart(vec![
            ContentPart::Text { text: "sys".into() },
            ContentPart::ImageUrl {
                image_url: ImageUrlPayload { url: image_data_uri(), detail: Some("high".into()) },
            },
        ]),
        name: None,
        tool_calls: None,
        tool_call_id: None,
        reasoning_content: None,
    }
}

/// Core contract: the vision model must accept the exact multipart shape rockbot
/// produces for a user attachment (`ChatMessage::user_with_images`, detail=high).
#[tokio::test]
#[ignore]
async fn deepseek_vision_model_accepts_image_url_parts() {
    let cfg = load_deepseek_config();
    cfg.validate_api_key()
        .expect("config.toml [chat_providers] deepseek api_key must be set (not EDITME)");
    eprintln!("DeepSeek base: {}", cfg.chat_url());

    let messages = vec![
        ChatMessage::system("You are a helpful assistant."),
        ChatMessage::user_with_images(
            "Attached: ![a.png](a.png)",
            vec![image_data_uri()],
        ),
    ];
    let body = chat_body(DEEPSEEK_VISION_MODEL, messages);
    let (status, resp) = post_chat(&cfg.chat_url(), &cfg.api_key, &body).await;

    eprintln!(
        "{}: HTTP {} — {}",
        DEEPSEEK_VISION_MODEL,
        status,
        resp.get("choices")
            .and_then(|c| c.as_array())
            .and_then(|c| c.first())
            .and_then(|c| c.get("message"))
            .and_then(|m| m.get("content"))
            .and_then(|v| v.as_str())
            .unwrap_or("(no content)")
    );
    assert_eq!(status, 200, "vision model must accept image_url parts: {resp}");
    let content = resp["choices"][0]["message"]["content"]
        .as_str()
        .unwrap_or_default();
    assert!(!content.is_empty(), "expected textual answer: {resp}");
}

/// Text-only DeepSeek models reject image parts — the provider's stripping path
/// must remain for them.
#[tokio::test]
#[ignore]
async fn deepseek_text_only_model_rejects_images() {
    let cfg = load_deepseek_config();

    let messages = vec![ChatMessage::user_with_images(
        "What color is this?",
        vec![image_data_uri()],
    )];
    let body = chat_body(DEEPSEEK_TEXT_MODEL, messages);
    let (status, resp) = post_chat(&cfg.chat_url(), &cfg.api_key, &body).await;

    let err = resp
        .get("error")
        .and_then(|e| e.get("message"))
        .and_then(|m| m.as_str())
        .unwrap_or_default();
    eprintln!("{DEEPSEEK_TEXT_MODEL}: HTTP {status} — {err}");
    assert_eq!(status, 400, "text-only model must reject images");
    assert!(
        err.to_lowercase().contains("image"),
        "error should mention image support: {err}"
    );
}

/// DeepSeek accepts images ONLY in user messages (docs + live): the forwarded
/// body post-fix must never put ImageUrl parts into system/assistant roles.
#[tokio::test]
#[ignore]
async fn deepseek_images_rejected_outside_user_role() {
    let cfg = load_deepseek_config();

    let assistant_body = chat_body(
        DEEPSEEK_VISION_MODEL,
        vec![
            ChatMessage::user("hi"),
            assistant_with_image(),
            ChatMessage::user("what color?"),
        ],
    );
    let (status_a, resp_a) = post_chat(&cfg.chat_url(), &cfg.api_key, &assistant_body).await;
    eprintln!("assistant image: HTTP {status_a} — {resp_a}");
    assert_eq!(status_a, 400);
    assert!(
        resp_a["error"]["message"]
            .as_str()
            .unwrap_or_default()
            .contains("assistant"),
        "expected assistant-message rejection: {resp_a}"
    );

    let system_body = chat_body(
        DEEPSEEK_VISION_MODEL,
        vec![system_with_image(), ChatMessage::user("hello")],
    );
    let (status_s, resp_s) = post_chat(&cfg.chat_url(), &cfg.api_key, &system_body).await;
    eprintln!("system image: HTTP {status_s} — {resp_s}");
    assert_eq!(status_s, 400);
    assert!(
        resp_s["error"]["message"]
            .as_str()
            .unwrap_or_default()
            .contains("system"),
        "expected system-message rejection: {resp_s}"
    );
}

/// The literal text "[image]" used by rockbot as a stripped-image placeholder is
/// NOT DeepSeek's reserved placeholder token — a plain-text "[image]" message is
/// accepted (200). This keeps memory summaries / old history with "[image]"
/// placeholders safe once the fix forwards images to the vision model.
#[tokio::test]
#[ignore]
async fn deepseek_placeholder_text_is_not_reserved_token() {
    let cfg = load_deepseek_config();

    let body = chat_body(
        DEEPSEEK_VISION_MODEL,
        vec![ChatMessage::user("What does [image] mean here? Reply in one word: placeholder")],
    );
    let (status, resp) = post_chat(&cfg.chat_url(), &cfg.api_key, &body).await;
    eprintln!("literal [image] text: HTTP {status} — {resp}");
    assert_eq!(status, 200, "literal [image] text must not trigger the reserved-token 400");
}

/// Per-image prompt-token cost must stay at/under DeepSeek's 384-image-token cap
/// so forwarding images (base64 data URIs) stays cheap.
#[tokio::test]
#[ignore]
async fn deepseek_image_token_cost_budget() {
    let cfg = load_deepseek_config();

    let baseline = chat_body(
        DEEPSEEK_VISION_MODEL,
        vec![ChatMessage::user("Reply in one word: ok")],
    );
    let (_, resp_base) = post_chat(&cfg.chat_url(), &cfg.api_key, &baseline).await;
    let base_prompt = resp_base["usage"]["prompt_tokens"].as_u64().unwrap_or(0);

    let with_img = chat_body(
        DEEPSEEK_VISION_MODEL,
        vec![ChatMessage::user_with_images("Reply in one word: ok", vec![image_data_uri()])],
    );
    let (status, resp_img) = post_chat(&cfg.chat_url(), &cfg.api_key, &with_img).await;
    assert_eq!(status, 200, "image request failed: {resp_img}");
    let img_prompt = resp_img["usage"]["prompt_tokens"].as_u64().unwrap_or(0);

    let delta = img_prompt.saturating_sub(base_prompt);
    eprintln!("prompt tokens: text-only={base_prompt}, with-image={img_prompt}, delta={delta}");
    assert!(
        delta > 0 && delta <= 384,
        "image token cost should be >0 and <=384, got {delta}"
    );
}
