[[chat_providers]]
name = "openrouter"
api_key = "sk-or-v1-EDITME"

[[chat_providers]]
name = "deepseek"
api_key = "EDITME"

[[image_providers]]
name = "openrouter"
api_key = "sk-or-v1-EDITME"

[[image_providers]]
name = "fal"
api_key = "EDITME"

[rocketchat.server]
url = "your-server.example.com"
username = "EDITME"
password = "EDITME"

[webdav]
url = "https://cloud.example.com"
username = "EDITME"
password = "EDITME"
root = "rockbot"

[tools.exa]
api_key = "EDITME"
